image: greenaddress/ci@sha256:ba2a76bb933f1da6573631597f947b1ff2f47e772674ab38c4e87e0eac6861b2

build_release_wheel:
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - apt install -yqq python3-venv
    - virtualenv -p python3 venv
    - source venv/bin/activate
    - pip install build
    - python -m build
    - deactivate
    - rm -rf venv
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 3 days
    paths:
    - $CI_PROJECT_DIR/dist
    when: on_success

.smoke_test:
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - virtualenv -p python3 venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install .
    - echo "paper mesh coyote doctor soon around first express street require clap knife turtle agree file fat engine cram exchange asthma carry tag replace under" >venv/mnemonic
    - green-cli -C ./venv --network testnet getbalance
    - deactivate
    - rm -rf venv

smoke_test_bullseye:
  extends: .smoke_test
  before_script:
    - if git grep '@click.option' | cut -d '(' -f 2 | cut -d ',' -f 1 | grep _; then echo 'ERROR - found disallowed underscored option(s)'; /bin/false; fi
    - pip install pycodestyle
    - pycodestyle */*.py */*/*.py --ignore=E501,E731,E302,E305

smoke_test_fedora:
  image: fedora:34@sha256:55a74d948c47bb002edff3c7a9a7e864152c686d7c2dc8e3df1ac4d611a20898
  extends: .smoke_test
  before_script:
    - dnf update -yq
    - dnf install -yq python-virtualenv python3-pip

smoke_test_osx:
  extends: .smoke_test
  tags:
    - osx
