image: greenaddress/ci@sha256:ba2a76bb933f1da6573631597f947b1ff2f47e772674ab38c4e87e0eac6861b2

.smoke_test:
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - virtualenv -p python3 venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install .
    - deactivate
    - rm -fr venv

smoke_test_bullseye:
  extends: .smoke_test
  before_script:
    - pip install pycodestyle
    - pycodestyle */*.py */*/*.py --ignore=E501,E731,E302,E305

smoke_test_fedora:
  image: fedora:34@sha256:55a74d948c47bb002edff3c7a9a7e864152c686d7c2dc8e3df1ac4d611a20898
  extends: .smoke_test
  before_script:
    - dnf update -yq
    - dnf install -yq python-virtualenv python3-pip

smoke_test_osx:
  extends: .smoke_test
  tags:
    - osx
