variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"
image: greenaddress/ci@sha256:ba2a76bb933f1da6573631597f947b1ff2f47e772674ab38c4e87e0eac6861b2

.smoke_test:
  cache:
    paths:
      - "$PIP_CACHE_DIR"
    key: "$CI_PROJECT_ID"
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - virtualenv -p python3 venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install .
    - deactivate
    - rm -fr venv

smoke_test_bullseye:
  extends: .smoke_test
  before_script:
    - pip install pycodestyle
    - pycodestyle */*.py */*/*.py --ignore=E501,E731,E302,E305
    - echo "Dir{Cache $PIP_CACHE_DIR}" >> /etc/apt/apt.conf
    - echo "Dir::Cache $PIP_CACHE_DIR;" >> /etc/apt/apt.conf
    - mkdir -p ${PIP_CACHE_DIR}/archives/partial
    - apt-get install --no-install-recommends -y -qq libusb-1.0-0-dev libudev-dev

smoke_test_fedora:
  image: fedora:33@sha256:46e6c941bb536f6a54390f9956e2566fde0738c28d21c16eb8daa16c22d13410
  extends: .smoke_test
  before_script:
    - rm -fr /var/cache/dnf
    - mkdir -p $PIP_CACHE_DIR
    - ln -s $PIP_CACHE_DIR /var/cache/dnf
    - dnf -y install libusb-devel libudev-devel python-virtualenv

smoke_test_osx:
  extends: .smoke_test
  tags:
    - osx
