image: blockstream/gdk-debian-ci@sha256:8c6e5eb5f164e45f09ef3f5374730e2b5488dbfc125f8a1fe96f15d6cbec7e30

build_release_wheel:
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - apt-get update -qq
    - apt-get install -yqq python3-venv
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install build twine
    - python -m build
    - twine check dist/*.whl
    - deactivate
    - rm -rf venv
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 3 days
    paths:
    - $CI_PROJECT_DIR/dist
    when: on_success

.smoke_test:
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - ${PYTHON_EXE:-python3} -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install .
    - echo "paper mesh coyote doctor soon around first express street require clap knife turtle agree file fat engine cram exchange asthma carry tag replace under" >venv/mnemonic
    - green-cli -C ./venv --network testnet getbalance
    - deactivate
    - rm -rf venv

.smoke_test_osx:
  extends: .smoke_test
  variables:
    PYTHON_EXE: python3.9

smoke_test_bullseye:
  extends: .smoke_test
  before_script:
    - apt-get update -qq
    - apt-get install -yqq python3-venv
    - if git grep '@click.option' | cut -d '(' -f 2 | cut -d ',' -f 1 | grep _; then echo 'ERROR - found disallowed underscored option(s)'; /bin/false; fi
    - pip install pycodestyle
    - pycodestyle */*.py */*/*.py --ignore=E501,E731,E302,E305

smoke_test_trixie:
  image: python:3.13-slim-trixie@sha256:27f90d79cc85e9b7b2560063ef44fa0e9eaae7a7c3f5a9f74563065c5477cc24
  extends: .smoke_test
  before_script:
    - apt-get update -qq
    - apt-get install -yqq python3-venv

smoke_test_fedora:
  image: fedora:34@sha256:55a74d948c47bb002edff3c7a9a7e864152c686d7c2dc8e3df1ac4d611a20898
  extends: .smoke_test
  before_script:
    - dnf update -yq
    - dnf install -yq python3 python3-pip

smoke_test_osx:
  extends: .smoke_test_osx
  parallel:
    matrix:
      - RUNNER: [ia, m4]
  tags:
    - osx-$RUNNER
