language: generic
sudo: required
services:
  - docker

env:
  global:
    - DOCKERBUILDER=greenaddress/ci
    - DOCKERHASH=bcf7f422c79b40127cf56f93184c7f8350aafe5de2ca2cfe7977c9b23c46f15c
    - UPDATE="apt-get update -qq && apt-get install --no-install-recommends -y -qq libusb-1.0-0-dev libudev-dev"
  matrix:
    - UNUSED=true
    - DOCKERBUILDER=greenaddress/fedora_ci DOCKERHASH=3d710f476b3d44376acc9fca6e26129e954053834f09ad4327756d67a232bd47 UPDATE="dnf -y install libusb-devel libudev-devel"

script:
  - docker run -v $PWD:/green_cli $DOCKERBUILDER@sha256:$DOCKERHASH /bin/bash -c "$UPDATE && cd /green_cli && virtualenv -p python3 venv && source venv/bin/activate && pip install -r requirements.txt && pip install . && python setup.py sdist"
